name = "eml-funnel"
main = "src/index.js"
compatibility_date = "2023-11-22"
account_id = "" 
kv_namespaces = [
  { binding = "KV", id = "" }
]
[vars]
GATEWAY_DOMAIN = "domain.com"
VAULT_EMAIL = "vault@domain.com"
GATEWAY_EMAIL = "gateway@domain.com"
PROCESSOR_SCHEMA = "https"
PROCESSOR_HOST = "processor.domain.com"
